name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install uv
        run: python -m pip install --upgrade uv
      - name: Set up environment
        run: |
          uv venv .venv
          uv pip install -r requirements.txt --python .venv/bin/python
      - name: Run tests
        run: .venv/bin/uv -m pytest -v
